organization_id = "738563006490"
billing_account = "01147F-8133D6-C2CB58"
user_id = "richard@lanreo.altostrat.com"
demo_folder_name = "VPC Service Controls Demo p"
data_project_id = "data-project-rzp"
consumer_project_a_id = "consumer-projecta-rzp"
consumer_project_b_id = "consumer-projectb-rzp"
cloud_storage_bucket_name = "cloud-storage-rtzp"
create_default_access_policy = false