organization_id = ""
billing_account = ""
user_id = "richard@lanreo.altostrat.com"
demo_folder_name = "VPC Service Controls Demo m"
data_project_id = "data-project-rzm"
consumer_project_a_id = "consumer-projecta-rzm"
consumer_project_b_id = "consumer-projectb-rzm"
cloud_storage_bucket_name = "cloud-storage-rtzm"
