organization_id = ""
billing_account = ""
demo_folder_name = "VPC Service Controls Demo g"
data_project_id = "data-project-rzg"
consumer_project_a_id = "consumer-projecta-rzg"
consumer_project_b_id = "consumer-projectb-rzg"
cloud_storage_bucket_name = "cloud-storage-rtzg"
